# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

target 'Infoapteka' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Infoapteka

  pod 'liquid-swipe'

  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  pod 'PinterestLayout'
  pod 'ImagePicker'

  pod 'MHWebViewController', '~> 1.0'
end
